[project]
name = "langchain-env"
version = "0.1.0"
description = "LangChain development environment"
requires-python = ">=3.10"
dependencies = [
    "langchain",
    "langchain-community>=0.4",
    "langchain-core>=1.0.1",
    "langchain-openai>=1.0.0a2",
    "pygame>=2.6.1",
]
